-- LOOPSCENE initial schema — MySQL 8.0 / Aurora MySQL 3.x.
--
-- Statements are separated by a line containing exactly `-- ;;`. MySQL DDL is
-- implicitly committed, so the runner sends one statement at a time; a trigger
-- body contains its own semicolons, which is why a plain `;` split will not do.
--
-- Design rules enforced here rather than in application code:
--   * every business object names its owner, so ownership checks cannot be
--     forgotten at the query site (SEC-01);
--   * JPY amounts are integers (§10);
--   * timestamps are DATETIME(3) holding UTC, rendered JST in the UI;
--   * audio blobs never live in the database — only storage keys and hashes;
--   * the credit ledger is append-only and the derived per-batch counters carry
--     CHECK constraints (enforced from 8.0.16), so an over-sell is a database
--     error rather than a silently negative balance (§6.2, GEN-03).
--
-- Ids are CHAR(36) ascii UUIDs generated by the application: MySQL has no
-- RETURNING, and generating the id up front avoids a read-back race.

CREATE TABLE users (
  id                CHAR(36) CHARACTER SET ascii NOT NULL,
  -- Cognito `sub` in integration/production; a deterministic local id in demo.
  external_id       VARCHAR(255)  NOT NULL,
  auth_provider     VARCHAR(32)   NOT NULL,
  email             VARCHAR(320)  NOT NULL,
  display_name      VARCHAR(120)  NULL,
  role              VARCHAR(16)   NOT NULL DEFAULT 'user',
  status            VARCHAR(16)   NOT NULL DEFAULT 'active',
  age_confirmed_at  DATETIME(3)   NULL,
  terms_accepted_at DATETIME(3)   NULL,
  -- SEC-11 / UI-02: marketing consent is separate from account use, default off.
  marketing_opt_in  TINYINT(1)    NOT NULL DEFAULT 0,
  created_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at        DATETIME(3)   NULL,
  -- MySQL has no partial indexes. A generated column that is NULL for deleted
  -- rows gives the same effect, because a unique index ignores NULLs.
  email_active      VARCHAR(320) GENERATED ALWAYS AS
                      (CASE WHEN deleted_at IS NULL THEN email END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY users_provider_subject_uk (auth_provider, external_id),
  UNIQUE KEY users_email_active_uk (email_active),
  CONSTRAINT users_role_chk   CHECK (role IN ('user','support','admin')),
  CONSTRAINT users_status_chk CHECK (status IN ('active','suspended','deleted'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE projects (
  id         CHAR(36) CHARACTER SET ascii NOT NULL,
  owner_id   CHAR(36) CHARACTER SET ascii NOT NULL,
  title      VARCHAR(200) NOT NULL,
  scene      VARCHAR(32)  NOT NULL,
  status     VARCHAR(16)  NOT NULL DEFAULT 'active',
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3)  NULL,
  PRIMARY KEY (id),
  KEY projects_owner_idx (owner_id, created_at DESC),
  CONSTRAINT projects_owner_fk FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT projects_status_chk CHECK (status IN ('active','deleted'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE entitlement_batches (
  id             CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id        CHAR(36) CHARACTER SET ascii NOT NULL,
  source         VARCHAR(32)  NOT NULL,
  -- Business key of the granting event: order id, "<sub>:<invoice>", etc.
  -- With the unique key below this is what stops a replayed Stripe event from
  -- granting a second batch (PAY-05).
  source_ref     VARCHAR(191) NOT NULL,
  product_key    VARCHAR(64)  NULL,
  price_version  INT          NULL,
  granted_units  INT          NOT NULL,
  reserved_units INT          NOT NULL DEFAULT 0,
  consumed_units INT          NOT NULL DEFAULT 0,
  effective_from DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  expires_at     DATETIME(3)  NULL,
  status         VARCHAR(16)  NOT NULL DEFAULT 'active',
  created_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY entitlement_batches_source_uk (user_id, source, source_ref),
  KEY entitlement_batches_available_idx (user_id, status, expires_at),
  CONSTRAINT entitlement_batches_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT entitlement_batches_source_chk CHECK (source IN
    ('one_time_order','subscription_period','promo_trial','compensation','manual_adjustment')),
  CONSTRAINT entitlement_batches_status_chk CHECK (status IN ('active','expired','revoked')),
  -- The balance invariant. No application path can drive a batch negative or
  -- oversell it without the statement failing.
  CONSTRAINT entitlement_batches_non_negative
    CHECK (granted_units >= 0 AND reserved_units >= 0 AND consumed_units >= 0),
  CONSTRAINT entitlement_batches_not_oversold
    CHECK (reserved_units + consumed_units <= granted_units)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE ledger_entries (
  id         CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id    CHAR(36) CHARACTER SET ascii NOT NULL,
  batch_id   CHAR(36) CHARACTER SET ascii NULL,
  job_id     CHAR(36) CHARACTER SET ascii NULL,
  entry_type VARCHAR(16)  NOT NULL,
  units      INT          NOT NULL,
  reason     VARCHAR(255) NOT NULL,
  -- Operator id for manual adjustments; NULL for system entries (§6.2).
  actor_id   CHAR(36) CHARACTER SET ascii NULL,
  metadata   JSON         NOT NULL,
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  -- Stands in for PostgreSQL's partial unique index. The value is NULL for
  -- entry types that may legitimately repeat, and a unique index ignores NULLs,
  -- so a job reserves at most once, consumes at most once and releases at most
  -- once. GEN-01/GEN-04/GEN-08 rely on this: a duplicated queue message or a
  -- repeated provider callback hits a duplicate-key error instead of
  -- double-charging.
  job_entry_uk CHAR(60) CHARACTER SET ascii GENERATED ALWAYS AS (
    CASE WHEN job_id IS NOT NULL
          AND entry_type IN ('reserve','consume','release','compensate')
         THEN CONCAT(job_id, ':', entry_type) END
  ) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY ledger_entries_job_type_uk (job_entry_uk),
  KEY ledger_entries_user_idx (user_id, created_at DESC),
  KEY ledger_entries_batch_idx (batch_id),
  KEY ledger_entries_job_idx (job_id),
  CONSTRAINT ledger_entries_user_fk  FOREIGN KEY (user_id)  REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT ledger_entries_batch_fk FOREIGN KEY (batch_id) REFERENCES entitlement_batches (id),
  CONSTRAINT ledger_entries_actor_fk FOREIGN KEY (actor_id) REFERENCES users (id),
  CONSTRAINT ledger_entries_type_chk CHECK (entry_type IN
    ('grant','reserve','consume','release','revoke','compensate','adjust')),
  CONSTRAINT ledger_entries_units_chk CHECK (units > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE generation_jobs (
  id                        CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id                   CHAR(36) CHARACTER SET ascii NOT NULL,
  project_id                CHAR(36) CHARACTER SET ascii NOT NULL,
  -- GEN-01/GEN-02: same key + same body returns the same job; same key +
  -- different body is a 409, decided by comparing request_hash.
  idempotency_key           VARCHAR(128) NOT NULL,
  request_hash              CHAR(64) CHARACTER SET ascii NOT NULL,
  state                     VARCHAR(16)  NOT NULL,
  input                     JSON         NOT NULL,
  resolved_params           JSON         NULL,
  provider_id               VARCHAR(64)  NULL,
  provider_model            VARCHAR(128) NULL,
  provider_contract_version VARCHAR(64)  NULL,
  -- Stable key sent upstream when the provider supports idempotency (GEN-06).
  provider_request_key      VARCHAR(128) NOT NULL,
  attempt_count             INT          NOT NULL DEFAULT 0,
  -- Optimistic concurrency guard; every state write bumps it (GEN-05).
  version                   INT          NOT NULL DEFAULT 0,
  lease_owner               VARCHAR(128) NULL,
  lease_expires_at          DATETIME(3)  NULL,
  cancel_requested_at       DATETIME(3)  NULL,
  track_id                  CHAR(36) CHARACTER SET ascii NULL,
  error_code                VARCHAR(64)  NULL,
  error_detail              VARCHAR(500) NULL,
  queued_at                 DATETIME(3)  NULL,
  submitted_at              DATETIME(3)  NULL,
  delivered_at              DATETIME(3)  NULL,
  finished_at               DATETIME(3)  NULL,
  -- When the job entered UNKNOWN; drives the reconciliation window (§12.3).
  verify_started_at         DATETIME(3)  NULL,
  created_at                DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at                DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY generation_jobs_idempotency_uk (user_id, idempotency_key),
  KEY generation_jobs_user_idx (user_id, created_at DESC),
  KEY generation_jobs_open_idx (state, lease_expires_at),
  KEY generation_jobs_track_idx (track_id),
  CONSTRAINT generation_jobs_user_fk    FOREIGN KEY (user_id)    REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT generation_jobs_project_fk FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
  CONSTRAINT generation_jobs_state_chk CHECK (state IN
    ('VALIDATING','RESERVED','QUEUED','SUBMITTED','UNKNOWN','PROCESSING',
     'DELIVERED','FAILED','REJECTED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE generation_attempts (
  id                  CHAR(36) CHARACTER SET ascii NOT NULL,
  job_id              CHAR(36) CHARACTER SET ascii NOT NULL,
  attempt_no          INT          NOT NULL,
  provider_id         VARCHAR(64)  NOT NULL,
  provider_model      VARCHAR(128) NULL,
  provider_request_id VARCHAR(191) NULL,
  -- Redacted envelopes. SEC-06: no keys, no raw prompt.
  request_payload     JSON         NOT NULL,
  response_payload    JSON         NULL,
  status              VARCHAR(16)  NOT NULL,
  error_code          VARCHAR(64)  NULL,
  started_at          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  finished_at         DATETIME(3)  NULL,
  PRIMARY KEY (id),
  UNIQUE KEY generation_attempts_job_no_uk (job_id, attempt_no),
  KEY generation_attempts_provider_req_idx (provider_id, provider_request_id),
  CONSTRAINT generation_attempts_job_fk FOREIGN KEY (job_id) REFERENCES generation_jobs (id) ON DELETE CASCADE,
  CONSTRAINT generation_attempts_status_chk CHECK (status IN
    ('started','submitted','succeeded','failed','rejected','unknown','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE tracks (
  id               CHAR(36) CHARACTER SET ascii NOT NULL,
  owner_id         CHAR(36) CHARACTER SET ascii NOT NULL,
  project_id       CHAR(36) CHARACTER SET ascii NOT NULL,
  job_id           CHAR(36) CHARACTER SET ascii NOT NULL,
  title            VARCHAR(200) NOT NULL,
  scene            VARCHAR(32)  NOT NULL,
  mood             VARCHAR(32)  NULL,
  duration_ms      INT          NOT NULL,
  state            VARCHAR(16)  NOT NULL DEFAULT 'processing',
  -- Set when a rights case suspends delivery; the UI shows it, downloads stop.
  suspended_reason VARCHAR(255) NULL,
  created_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at       DATETIME(3)  NULL,
  PRIMARY KEY (id),
  UNIQUE KEY tracks_job_uk (job_id),
  KEY tracks_owner_idx (owner_id, created_at DESC),
  KEY tracks_project_idx (project_id),
  CONSTRAINT tracks_owner_fk   FOREIGN KEY (owner_id)   REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT tracks_project_fk FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
  CONSTRAINT tracks_job_fk     FOREIGN KEY (job_id)     REFERENCES generation_jobs (id) ON DELETE CASCADE,
  CONSTRAINT tracks_state_chk CHECK (state IN ('processing','deliverable','suspended','deleted')),
  CONSTRAINT tracks_duration_chk CHECK (duration_ms > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

ALTER TABLE generation_jobs
  ADD CONSTRAINT generation_jobs_track_fk
  FOREIGN KEY (track_id) REFERENCES tracks (id) ON DELETE SET NULL
-- ;;

CREATE TABLE asset_versions (
  id               CHAR(36) CHARACTER SET ascii NOT NULL,
  track_id         CHAR(36) CHARACTER SET ascii NOT NULL,
  owner_id         CHAR(36) CHARACTER SET ascii NOT NULL,
  kind             VARCHAR(16)  NOT NULL,
  format           VARCHAR(8)   NOT NULL,
  storage_key      VARCHAR(512) NOT NULL,
  byte_size        BIGINT       NOT NULL,
  duration_ms      INT          NOT NULL,
  sha256           CHAR(64) CHARACTER SET ascii NOT NULL,
  clip_start_ms    INT          NULL,
  clip_duration_ms INT          NULL,
  fade_out_ms      INT          NOT NULL DEFAULT 0,
  -- Canonical hash of the export parameters, so an identical re-export reuses
  -- the existing object instead of re-rendering (UI-06: repeat download is free).
  params_hash      VARCHAR(64) CHARACTER SET ascii NOT NULL,
  created_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY asset_versions_variant_uk (track_id, kind, params_hash),
  KEY asset_versions_owner_idx (owner_id),
  CONSTRAINT asset_versions_track_fk FOREIGN KEY (track_id) REFERENCES tracks (id) ON DELETE CASCADE,
  CONSTRAINT asset_versions_owner_fk FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT asset_versions_kind_chk   CHECK (kind IN ('master','quarantine','export')),
  CONSTRAINT asset_versions_format_chk CHECK (format IN ('mp3','wav')),
  CONSTRAINT asset_versions_size_chk   CHECK (byte_size > 0 AND duration_ms > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE license_snapshots (
  id                  CHAR(36) CHARACTER SET ascii NOT NULL,
  track_id            CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id             CHAR(36) CHARACTER SET ascii NOT NULL,
  provider_id         VARCHAR(64)  NOT NULL,
  provider_model      VARCHAR(128) NOT NULL,
  -- Upstream contract version in force at generation time. SEC-08: a later
  -- contract must not silently rewrite what an existing track was granted.
  contract_version    VARCHAR(64)  NOT NULL,
  license_version     VARCHAR(64)  NOT NULL,
  territory           VARCHAR(16)  NOT NULL,
  allowed_uses        JSON         NOT NULL,
  prohibited_uses     JSON         NOT NULL,
  source_sha256       CHAR(64) CHARACTER SET ascii NOT NULL,
  generated_at        DATETIME(3)  NOT NULL,
  commercial_delivery TINYINT(1)   NOT NULL DEFAULT 0,
  status              VARCHAR(16)  NOT NULL DEFAULT 'active',
  status_reason       VARCHAR(255) NULL,
  created_at          DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY license_snapshots_track_uk (track_id),
  CONSTRAINT license_snapshots_track_fk FOREIGN KEY (track_id) REFERENCES tracks (id) ON DELETE CASCADE,
  CONSTRAINT license_snapshots_user_fk  FOREIGN KEY (user_id)  REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT license_snapshots_status_chk CHECK (status IN ('active','suspended','revoked'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

-- Immutability guard: only `status` and `status_reason` may ever change, so a
-- new commercial agreement cannot retroactively overwrite the terms a user
-- generated under (SEC-08).
CREATE TRIGGER license_snapshots_freeze
BEFORE UPDATE ON license_snapshots
FOR EACH ROW
BEGIN
  IF NEW.track_id            <=> OLD.track_id            = 0
  OR NEW.user_id             <=> OLD.user_id             = 0
  OR NEW.provider_id         <=> OLD.provider_id         = 0
  OR NEW.provider_model      <=> OLD.provider_model      = 0
  OR NEW.contract_version    <=> OLD.contract_version    = 0
  OR NEW.license_version     <=> OLD.license_version     = 0
  OR NEW.territory           <=> OLD.territory           = 0
  OR NEW.source_sha256       <=> OLD.source_sha256       = 0
  OR NEW.generated_at        <=> OLD.generated_at        = 0
  OR NEW.commercial_delivery <=> OLD.commercial_delivery = 0
  OR CAST(NEW.allowed_uses AS CHAR)    <=> CAST(OLD.allowed_uses AS CHAR)    = 0
  OR CAST(NEW.prohibited_uses AS CHAR) <=> CAST(OLD.prohibited_uses AS CHAR) = 0
  THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'license_snapshots are immutable except status/status_reason';
  END IF;
END
-- ;;

CREATE TABLE product_catalog (
  price_key       VARCHAR(64)  NOT NULL,
  version         INT          NOT NULL,
  kind            VARCHAR(16)  NOT NULL,
  display_name    VARCHAR(120) NOT NULL,
  amount_jpy      INT          NOT NULL,
  currency        VARCHAR(8)   NOT NULL DEFAULT 'jpy',
  tax_included    TINYINT(1)   NOT NULL DEFAULT 1,
  units           INT          NOT NULL,
  validity_days   INT          NULL,
  auto_renew      TINYINT(1)   NOT NULL DEFAULT 0,
  stripe_price_id VARCHAR(191) NULL,
  active          TINYINT(1)   NOT NULL DEFAULT 1,
  created_at      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (price_key, version),
  CONSTRAINT product_catalog_kind_chk   CHECK (kind IN ('one_time','subscription')),
  CONSTRAINT product_catalog_amount_chk CHECK (amount_jpy >= 0 AND units > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE orders (
  id                         CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id                    CHAR(36) CHARACTER SET ascii NOT NULL,
  price_key                  VARCHAR(64)  NOT NULL,
  price_version              INT          NOT NULL,
  kind                       VARCHAR(16)  NOT NULL,
  amount_jpy                 INT          NOT NULL,
  currency                   VARCHAR(8)   NOT NULL DEFAULT 'jpy',
  status                     VARCHAR(24)  NOT NULL DEFAULT 'pending',
  idempotency_key            VARCHAR(128) NOT NULL,
  stripe_checkout_session_id VARCHAR(191) NULL,
  stripe_payment_intent_id   VARCHAR(191) NULL,
  stripe_customer_id         VARCHAR(191) NULL,
  entitlement_granted_at     DATETIME(3)  NULL,
  paid_at                    DATETIME(3)  NULL,
  receipt_url                VARCHAR(512) NULL,
  refunded_amount_jpy        INT          NOT NULL DEFAULT 0,
  metadata                   JSON         NOT NULL,
  created_at                 DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at                 DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY orders_idempotency_uk (user_id, idempotency_key),
  UNIQUE KEY orders_session_uk (stripe_checkout_session_id),
  UNIQUE KEY orders_intent_uk (stripe_payment_intent_id),
  KEY orders_user_idx (user_id, created_at DESC),
  KEY orders_product_idx (price_key, price_version),
  CONSTRAINT orders_user_fk    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT orders_product_fk FOREIGN KEY (price_key, price_version)
    REFERENCES product_catalog (price_key, version),
  CONSTRAINT orders_kind_chk   CHECK (kind IN ('one_time','subscription')),
  CONSTRAINT orders_status_chk CHECK (status IN
    ('pending','paid','failed','refunded','partially_refunded','canceled')),
  CONSTRAINT orders_amount_chk CHECK (amount_jpy >= 0 AND refunded_amount_jpy >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE payments (
  id               CHAR(36) CHARACTER SET ascii NOT NULL,
  order_id         CHAR(36) CHARACTER SET ascii NULL,
  user_id          CHAR(36) CHARACTER SET ascii NOT NULL,
  kind             VARCHAR(16)  NOT NULL,
  -- Stripe object id (pi_…, re_…, dp_…). PAY-11 reconciliation key.
  stripe_object_id VARCHAR(191) NOT NULL,
  amount_jpy       INT          NOT NULL,
  fee_jpy          INT          NOT NULL DEFAULT 0,
  net_jpy          INT          NOT NULL DEFAULT 0,
  currency         VARCHAR(8)   NOT NULL DEFAULT 'jpy',
  status           VARCHAR(32)  NOT NULL,
  payout_id        VARCHAR(191) NULL,
  occurred_at      DATETIME(3)  NOT NULL,
  raw              JSON         NOT NULL,
  created_at       DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY payments_object_uk (kind, stripe_object_id),
  KEY payments_order_idx (order_id),
  CONSTRAINT payments_order_fk FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL,
  CONSTRAINT payments_user_fk  FOREIGN KEY (user_id)  REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT payments_kind_chk CHECK (kind IN ('payment','refund','dispute','fee'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE subscriptions (
  id                     CHAR(36) CHARACTER SET ascii NOT NULL,
  user_id                CHAR(36) CHARACTER SET ascii NOT NULL,
  stripe_subscription_id VARCHAR(191) NOT NULL,
  stripe_customer_id     VARCHAR(191) NOT NULL,
  price_key              VARCHAR(64)  NOT NULL,
  price_version          INT          NOT NULL,
  status                 VARCHAR(24)  NOT NULL,
  current_period_start   DATETIME(3)  NULL,
  current_period_end     DATETIME(3)  NULL,
  cancel_at_period_end   TINYINT(1)   NOT NULL DEFAULT 0,
  canceled_at            DATETIME(3)  NULL,
  latest_invoice_id      VARCHAR(191) NULL,
  -- Guards against an out-of-order webhook overwriting newer state (PAY-05).
  last_event_at          DATETIME(3)  NULL,
  created_at             DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at             DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY subscriptions_stripe_uk (stripe_subscription_id),
  KEY subscriptions_user_idx (user_id),
  CONSTRAINT subscriptions_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE provider_cost_events (
  id               CHAR(36) CHARACTER SET ascii NOT NULL,
  job_id           CHAR(36) CHARACTER SET ascii NULL,
  attempt_id       CHAR(36) CHARACTER SET ascii NULL,
  provider_id      VARCHAR(64) NOT NULL,
  provider_kind    VARCHAR(16) NOT NULL,
  event_type       VARCHAR(24) NOT NULL,
  -- AI-06: billability comes from the configured contract, never defaulted to
  -- "failures are free". `cost_minor` is a modelled figure in demo mode and is
  -- flagged as such by `is_estimate`.
  billable         TINYINT(1)  NOT NULL,
  cost_minor       INT         NOT NULL DEFAULT 0,
  currency         VARCHAR(8)  NOT NULL DEFAULT 'jpy',
  is_estimate      TINYINT(1)  NOT NULL DEFAULT 1,
  contract_version VARCHAR(64) NULL,
  -- `usage` is a reserved word in MySQL, hence the suffix.
  usage_data       JSON        NOT NULL,
  occurred_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY provider_cost_events_job_idx (job_id),
  KEY provider_cost_events_time_idx (occurred_at),
  CONSTRAINT provider_cost_events_job_fk FOREIGN KEY (job_id) REFERENCES generation_jobs (id) ON DELETE SET NULL,
  CONSTRAINT provider_cost_events_attempt_fk FOREIGN KEY (attempt_id) REFERENCES generation_attempts (id) ON DELETE SET NULL,
  CONSTRAINT provider_cost_events_kind_chk CHECK (provider_kind IN ('music','text')),
  CONSTRAINT provider_cost_events_type_chk CHECK (event_type IN
    ('success','failure','rejected','retry','late_success','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE outbox (
  id             CHAR(36) CHARACTER SET ascii NOT NULL,
  aggregate_type VARCHAR(64)  NOT NULL,
  aggregate_id   CHAR(36) CHARACTER SET ascii NOT NULL,
  event_type     VARCHAR(64)  NOT NULL,
  payload        JSON         NOT NULL,
  status         VARCHAR(16)  NOT NULL DEFAULT 'pending',
  attempts       INT          NOT NULL DEFAULT 0,
  available_at   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  dispatched_at  DATETIME(3)  NULL,
  last_error     VARCHAR(500) NULL,
  created_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY outbox_pending_idx (status, available_at),
  CONSTRAINT outbox_status_chk CHECK (status IN ('pending','dispatched','failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE webhook_events (
  id                 CHAR(36) CHARACTER SET ascii NOT NULL,
  provider           VARCHAR(16)  NOT NULL,
  -- PAY-05 first idempotency layer: the event id itself.
  event_id           VARCHAR(191) NOT NULL,
  event_type         VARCHAR(128) NOT NULL,
  signature_verified TINYINT(1)   NOT NULL,
  payload            JSON         NOT NULL,
  status             VARCHAR(16)  NOT NULL DEFAULT 'received',
  attempts           INT          NOT NULL DEFAULT 0,
  last_error         VARCHAR(500) NULL,
  received_at        DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  processed_at       DATETIME(3)  NULL,
  PRIMARY KEY (id),
  UNIQUE KEY webhook_events_provider_event_uk (provider, event_id),
  KEY webhook_events_status_idx (status, received_at),
  CONSTRAINT webhook_events_provider_chk CHECK (provider IN ('stripe','music')),
  CONSTRAINT webhook_events_status_chk CHECK (status IN
    ('received','processing','processed','failed','ignored'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

-- Local, database-backed stand-in for SQS. Same at-least-once semantics
-- (visibility timeout, redelivery, DLQ) so the worker code path is identical
-- (§4.2). Passing tests here is not evidence that real SQS was verified.
CREATE TABLE local_queue_messages (
  id             CHAR(36) CHARACTER SET ascii NOT NULL,
  queue_name     VARCHAR(64) NOT NULL,
  body           JSON        NOT NULL,
  receipt_handle CHAR(36) CHARACTER SET ascii NULL,
  visible_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  receive_count  INT         NOT NULL DEFAULT 0,
  dead_lettered  TINYINT(1)  NOT NULL DEFAULT 0,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY local_queue_visible_idx (queue_name, dead_lettered, visible_at),
  KEY local_queue_receipt_idx (receipt_handle)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE rights_cases (
  id             CHAR(36) CHARACTER SET ascii NOT NULL,
  case_number    VARCHAR(32)  NOT NULL,
  track_id       CHAR(36) CHARACTER SET ascii NULL,
  audio_sha256   CHAR(64) CHARACTER SET ascii NULL,
  reporter_name  VARCHAR(120) NOT NULL,
  reporter_email VARCHAR(320) NOT NULL,
  claim_type     VARCHAR(32)  NOT NULL,
  description    TEXT         NOT NULL,
  evidence       JSON         NOT NULL,
  status         VARCHAR(16)  NOT NULL DEFAULT 'received',
  assigned_to    CHAR(36) CHARACTER SET ascii NULL,
  resolution     VARCHAR(500) NULL,
  created_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY rights_cases_number_uk (case_number),
  KEY rights_cases_status_idx (status, created_at DESC),
  KEY rights_cases_track_idx (track_id),
  CONSTRAINT rights_cases_track_fk    FOREIGN KEY (track_id)    REFERENCES tracks (id) ON DELETE SET NULL,
  CONSTRAINT rights_cases_assignee_fk FOREIGN KEY (assigned_to) REFERENCES users (id),
  CONSTRAINT rights_cases_status_chk CHECK (status IN
    ('received','under_review','suspended','dismissed','upheld','restored'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE audit_logs (
  id           CHAR(36) CHARACTER SET ascii NOT NULL,
  actor_id     CHAR(36) CHARACTER SET ascii NULL,
  actor_role   VARCHAR(16)  NOT NULL,
  action       VARCHAR(64)  NOT NULL,
  subject_type VARCHAR(32)  NOT NULL,
  subject_id   VARCHAR(191) NOT NULL,
  -- UI-15: a privileged action without a stated reason cannot be recorded.
  reason       VARCHAR(500) NOT NULL,
  before_state JSON         NULL,
  after_state  JSON         NULL,
  ip_hash      CHAR(64) CHARACTER SET ascii NULL,
  created_at   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY audit_logs_subject_idx (subject_type, subject_id, created_at DESC),
  KEY audit_logs_actor_idx (actor_id, created_at DESC),
  CONSTRAINT audit_logs_actor_fk FOREIGN KEY (actor_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

CREATE TABLE analytics_events (
  id            CHAR(36) CHARACTER SET ascii NOT NULL,
  name          VARCHAR(64)  NOT NULL,
  -- §11.1: pseudonymous user reference, never the email address.
  user_ref      VARCHAR(191) NULL,
  occurred_at   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  props         JSON         NOT NULL,
  price_version INT          NULL,
  run_mode      VARCHAR(16)  NOT NULL,
  -- Demo/internal traffic is flagged so reporting can exclude it (§11.1).
  is_internal   TINYINT(1)   NOT NULL DEFAULT 0,
  created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY analytics_events_name_idx (name, occurred_at),
  KEY analytics_events_user_idx (user_ref, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
-- ;;

-- Server-side, versioned operational switches (§3.2 "运营"). The API reads
-- these at request time so an operator can stop new generation without a deploy.
-- `key`/`value` are reserved words in MySQL, hence the prefixes.
CREATE TABLE runtime_settings (
  setting_key   VARCHAR(64)  NOT NULL,
  setting_value JSON         NOT NULL,
  updated_by    CHAR(36) CHARACTER SET ascii NULL,
  reason        VARCHAR(500) NULL,
  updated_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (setting_key),
  CONSTRAINT runtime_settings_actor_fk FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
